// ARQUIVO GERADO por ferramentas/gerar_catalogo.py — não edite aqui.
// Para mudar o catálogo, edite ferramentas/catalogo.csv e rode o script de novo.
const JOGOS = [
  {"id": "god-of-war", "titulo": "God of War", "genero": "Aventura", "tamanho": 45, "ranking": 17, "capa": "capas/god-of-war.jpg"},
  {"id": "god-of-war-ragnarok", "titulo": "God of War Ragnarök", "genero": "Aventura", "tamanho": 90, "ranking": 3, "capa": "capas/god-of-war-ragnarok.jpg"},
  {"id": "god-of-war-iii-remastered", "titulo": "God of War III Remastered", "genero": "Ação", "tamanho": 40, "ranking": 28, "capa": "capas/god-of-war-iii-remastered.jpg"},
  {"id": "marvel-s-spider-man", "titulo": "Marvel's Spider-Man", "genero": "Ação", "tamanho": 50, "ranking": 4, "capa": "capas/marvel-s-spider-man.jpg"},
  {"id": "marvel-s-spider-man-miles-morales", "titulo": "Marvel's Spider-Man: Miles Morales", "genero": "Ação", "tamanho": 50, "capa": "capas/marvel-s-spider-man-miles-morales.jpg"},
  {"id": "the-last-of-us-remastered", "titulo": "The Last of Us Remastered", "genero": "Aventura", "tamanho": 50, "ranking": 19, "capa": "capas/the-last-of-us-remastered.jpg"},
  {"id": "the-last-of-us-part-ii", "titulo": "The Last of Us Part II", "genero": "Aventura", "tamanho": 100, "ranking": 6, "capa": "capas/the-last-of-us-part-ii.jpg"},
  {"id": "uncharted-4-a-thief-s-end", "titulo": "Uncharted 4: A Thief's End", "genero": "Aventura", "tamanho": 65, "ranking": 7, "capa": "capas/uncharted-4-a-thief-s-end.jpg"},
  {"id": "uncharted-the-lost-legacy", "titulo": "Uncharted: The Lost Legacy", "genero": "Aventura", "tamanho": 50, "ranking": 31, "capa": "capas/uncharted-the-lost-legacy.jpg"},
  {"id": "uncharted-the-nathan-drake-collection", "titulo": "Uncharted: The Nathan Drake Collection", "genero": "Aventura", "tamanho": 50, "ranking": 22, "capa": "capas/uncharted-the-nathan-drake-collection.jpg"},
  {"id": "horizon-zero-dawn-complete-edition", "titulo": "Horizon Zero Dawn Complete Edition", "genero": "Aventura", "tamanho": 70, "ranking": 18, "capa": "capas/horizon-zero-dawn-complete-edition.jpg"},
  {"id": "horizon-forbidden-west", "titulo": "Horizon Forbidden West", "genero": "Aventura", "tamanho": 90, "ranking": 16, "capa": "capas/horizon-forbidden-west.jpg"},
  {"id": "ghost-of-tsushima", "titulo": "Ghost of Tsushima", "genero": "Aventura", "tamanho": 60, "ranking": 5, "capa": "capas/ghost-of-tsushima.jpg"},
  {"id": "days-gone", "titulo": "Days Gone", "genero": "Ação", "tamanho": 70, "ranking": 12, "capa": "capas/days-gone.jpg"},
  {"id": "bloodborne", "titulo": "Bloodborne", "genero": "RPG", "tamanho": 35, "ranking": 23, "capa": "capas/bloodborne.jpg"},
  {"id": "gran-turismo-7", "titulo": "Gran Turismo 7", "genero": "Corrida", "tamanho": 110, "capa": "capas/gran-turismo-7.jpg"},
  {"id": "gran-turismo-sport", "titulo": "Gran Turismo Sport", "genero": "Corrida", "tamanho": 100, "ranking": 21, "capa": "capas/gran-turismo-sport.jpg"},
  {"id": "infamous-second-son", "titulo": "inFAMOUS Second Son", "genero": "Ação", "tamanho": 30, "ranking": 27, "capa": "capas/infamous-second-son.jpg"},
  {"id": "detroit-become-human", "titulo": "Detroit: Become Human", "genero": "Aventura", "tamanho": 55, "ranking": 29, "capa": "capas/detroit-become-human.jpg"},
  {"id": "until-dawn", "titulo": "Until Dawn", "genero": "Terror", "tamanho": 45, "ranking": 37, "capa": "capas/until-dawn.jpg"},
  {"id": "death-stranding", "titulo": "Death Stranding", "genero": "Aventura", "tamanho": 70, "ranking": 35, "capa": "capas/death-stranding.jpg"},
  {"id": "ratchet-clank", "titulo": "Ratchet & Clank", "genero": "Plataforma", "tamanho": 40, "ranking": 24, "capa": "capas/ratchet-clank.jpg"},
  {"id": "sackboy-uma-grande-aventura", "titulo": "Sackboy: Uma Grande Aventura", "genero": "Plataforma", "tamanho": 30, "capa": "capas/sackboy-uma-grande-aventura.jpg"},
  {"id": "littlebigplanet-3", "titulo": "LittleBigPlanet 3", "genero": "Plataforma", "tamanho": 15, "ranking": 30, "capa": "capas/littlebigplanet-3.jpg"},
  {"id": "concrete-genie", "titulo": "Concrete Genie", "genero": "Aventura", "tamanho": 10, "capa": "capas/concrete-genie.jpg"},
  {"id": "shadow-of-the-colossus", "titulo": "Shadow of the Colossus", "genero": "Aventura", "tamanho": 10, "capa": "capas/shadow-of-the-colossus.jpg"},
  {"id": "the-order-1886", "titulo": "The Order: 1886", "genero": "Ação", "tamanho": 40, "capa": "capas/the-order-1886.jpg"},
  {"id": "medievil", "titulo": "MediEvil", "genero": "Aventura", "tamanho": 10, "capa": "capas/medievil.jpg"},
  {"id": "killzone-shadow-fall", "titulo": "Killzone Shadow Fall", "genero": "Tiro", "tamanho": 50, "capa": "capas/killzone-shadow-fall.jpg"},
  {"id": "driveclub", "titulo": "Driveclub", "genero": "Corrida", "tamanho": 50, "ranking": 33, "capa": "capas/driveclub.jpg"},
  {"id": "crash-bandicoot-n-sane-trilogy", "titulo": "Crash Bandicoot N. Sane Trilogy", "genero": "Plataforma", "tamanho": 30, "capa": "capas/crash-bandicoot-n-sane-trilogy.jpg"},
  {"id": "crash-bandicoot-4-it-s-about-time", "titulo": "Crash Bandicoot 4: It's About Time", "genero": "Plataforma", "tamanho": 30, "capa": "capas/crash-bandicoot-4-it-s-about-time.jpg"},
  {"id": "crash-team-racing-nitro-fueled", "titulo": "Crash Team Racing Nitro-Fueled", "genero": "Corrida", "tamanho": 25, "capa": "capas/crash-team-racing-nitro-fueled.jpg"},
  {"id": "spyro-reignited-trilogy", "titulo": "Spyro Reignited Trilogy", "genero": "Plataforma", "tamanho": 40, "capa": "capas/spyro-reignited-trilogy.jpg"},
  {"id": "gta-v", "titulo": "GTA V", "genero": "Ação", "tamanho": 95, "ranking": 2, "capa": "capas/gta-v.jpg"},
  {"id": "red-dead-redemption-2", "titulo": "Red Dead Redemption 2", "genero": "Ação", "tamanho": 120, "ranking": 1, "capa": "capas/red-dead-redemption-2.jpg"},
  {"id": "red-dead-redemption", "titulo": "Red Dead Redemption", "genero": "Ação", "tamanho": 10, "capa": "capas/red-dead-redemption.jpg"},
  {"id": "gta-the-trilogy-definitive-edition", "titulo": "GTA: The Trilogy – Definitive Edition", "genero": "Ação", "tamanho": 25, "capa": "capas/gta-the-trilogy-definitive-edition.jpg"},
  {"id": "l-a-noire", "titulo": "L.A. Noire", "genero": "Aventura", "tamanho": 40, "capa": "capas/l-a-noire.jpg"},
  {"id": "bully", "titulo": "Bully", "genero": "Ação", "tamanho": 10, "capa": "capas/bully.jpg"},
  {"id": "assassin-s-creed-iv-black-flag", "titulo": "Assassin's Creed IV: Black Flag", "genero": "Ação", "tamanho": 30, "capa": "capas/assassin-s-creed-iv-black-flag.jpg"},
  {"id": "assassin-s-creed-unity", "titulo": "Assassin's Creed Unity", "genero": "Ação", "tamanho": 50, "capa": "capas/assassin-s-creed-unity.jpg"},
  {"id": "assassin-s-creed-syndicate", "titulo": "Assassin's Creed Syndicate", "genero": "Ação", "tamanho": 50, "capa": "capas/assassin-s-creed-syndicate.jpg"},
  {"id": "assassin-s-creed-origins", "titulo": "Assassin's Creed Origins", "genero": "RPG", "tamanho": 70, "capa": "capas/assassin-s-creed-origins.jpg"},
  {"id": "assassin-s-creed-odyssey", "titulo": "Assassin's Creed Odyssey", "genero": "RPG", "tamanho": 90, "capa": "capas/assassin-s-creed-odyssey.jpg"},
  {"id": "assassin-s-creed-valhalla", "titulo": "Assassin's Creed Valhalla", "genero": "RPG", "tamanho": 100, "capa": "capas/assassin-s-creed-valhalla.jpg"},
  {"id": "assassin-s-creed-mirage", "titulo": "Assassin's Creed Mirage", "genero": "Ação", "tamanho": 40, "capa": "capas/assassin-s-creed-mirage.jpg"},
  {"id": "assassin-s-creed-the-ezio-collection", "titulo": "Assassin's Creed: The Ezio Collection", "genero": "Ação", "tamanho": 30},
  {"id": "far-cry-4", "titulo": "Far Cry 4", "genero": "Tiro", "tamanho": 40, "capa": "capas/far-cry-4.jpg"},
  {"id": "far-cry-5", "titulo": "Far Cry 5", "genero": "Tiro", "tamanho": 45, "capa": "capas/far-cry-5.jpg"},
  {"id": "far-cry-6", "titulo": "Far Cry 6", "genero": "Tiro", "tamanho": 70, "capa": "capas/far-cry-6.jpg"},
  {"id": "far-cry-primal", "titulo": "Far Cry Primal", "genero": "Ação", "tamanho": 25, "capa": "capas/far-cry-primal.jpg"},
  {"id": "far-cry-new-dawn", "titulo": "Far Cry New Dawn", "genero": "Tiro", "tamanho": 40, "capa": "capas/far-cry-new-dawn.jpg"},
  {"id": "watch-dogs", "titulo": "Watch Dogs", "genero": "Ação", "tamanho": 25, "capa": "capas/watch-dogs.jpg"},
  {"id": "watch-dogs-2", "titulo": "Watch Dogs 2", "genero": "Ação", "tamanho": 50, "capa": "capas/watch-dogs-2.jpg"},
  {"id": "watch-dogs-legion", "titulo": "Watch Dogs: Legion", "genero": "Ação", "tamanho": 50, "capa": "capas/watch-dogs-legion.jpg"},
  {"id": "tom-clancy-s-the-division-2", "titulo": "Tom Clancy's The Division 2", "genero": "Tiro", "tamanho": 90, "capa": "capas/tom-clancy-s-the-division-2.jpg"},
  {"id": "rainbow-six-siege", "titulo": "Rainbow Six Siege", "genero": "Tiro", "tamanho": 80, "capa": "capas/rainbow-six-siege.jpg"},
  {"id": "ghost-recon-wildlands", "titulo": "Ghost Recon Wildlands", "genero": "Tiro", "tamanho": 60, "capa": "capas/ghost-recon-wildlands.jpg"},
  {"id": "ghost-recon-breakpoint", "titulo": "Ghost Recon Breakpoint", "genero": "Tiro", "tamanho": 70, "capa": "capas/ghost-recon-breakpoint.jpg"},
  {"id": "immortals-fenyx-rising", "titulo": "Immortals Fenyx Rising", "genero": "Aventura", "tamanho": 35, "capa": "capas/immortals-fenyx-rising.jpg"},
  {"id": "prince-of-persia-the-lost-crown", "titulo": "Prince of Persia: The Lost Crown", "genero": "Plataforma", "tamanho": 10, "capa": "capas/prince-of-persia-the-lost-crown.jpg"},
  {"id": "rayman-legends", "titulo": "Rayman Legends", "genero": "Plataforma", "tamanho": 6, "capa": "capas/rayman-legends.jpg"},
  {"id": "the-crew-2", "titulo": "The Crew 2", "genero": "Corrida", "tamanho": 30, "capa": "capas/the-crew-2.jpg"},
  {"id": "steep", "titulo": "Steep", "genero": "Esporte", "tamanho": 25, "capa": "capas/steep.jpg"},
  {"id": "riders-republic", "titulo": "Riders Republic", "genero": "Esporte", "tamanho": 35, "capa": "capas/riders-republic.jpg"},
  {"id": "for-honor", "titulo": "For Honor", "genero": "Luta", "tamanho": 60, "capa": "capas/for-honor.jpg"},
  {"id": "south-park-a-fenda-que-abunda-forca", "titulo": "South Park: A Fenda que Abunda Força", "genero": "RPG", "tamanho": 20, "capa": "capas/south-park-a-fenda-que-abunda-forca.jpg"},
  {"id": "ea-sports-fc-27", "titulo": "EA Sports FC 27", "genero": "Esporte", "tamanho": 50, "ranking": 9, "capa": "capas/ea-sports-fc-27.jpg"},
  {"id": "ea-sports-fc-26", "titulo": "EA Sports FC 26", "genero": "Esporte", "tamanho": 50, "capa": "capas/ea-sports-fc-26.jpg"},
  {"id": "pes-2021", "titulo": "PES 2021", "genero": "Esporte", "tamanho": 45, "ranking": 10, "capa": "capas/pes-2021.jpg"},
  {"id": "ea-sports-fc-25", "titulo": "EA Sports FC 25", "genero": "Esporte", "tamanho": 50, "capa": "capas/ea-sports-fc-25.jpg"},
  {"id": "ea-sports-fc-24", "titulo": "EA Sports FC 24", "genero": "Esporte", "tamanho": 50, "capa": "capas/ea-sports-fc-24.jpg"},
  {"id": "fifa-23", "titulo": "FIFA 23", "genero": "Esporte", "tamanho": 50, "capa": "capas/fifa-23.jpg"},
  {"id": "ufc-4", "titulo": "UFC 4", "genero": "Luta", "tamanho": 25, "capa": "capas/ufc-4.jpg"},
  {"id": "need-for-speed-heat", "titulo": "Need for Speed Heat", "genero": "Corrida", "tamanho": 50, "capa": "capas/need-for-speed-heat.jpg"},
  {"id": "need-for-speed-payback", "titulo": "Need for Speed Payback", "genero": "Corrida", "tamanho": 30, "capa": "capas/need-for-speed-payback.jpg"},
  {"id": "need-for-speed-2015", "titulo": "Need for Speed (2015)", "genero": "Corrida", "tamanho": 30, "capa": "capas/need-for-speed-2015.jpg"},
  {"id": "need-for-speed-hot-pursuit-remastered", "titulo": "Need for Speed Hot Pursuit Remastered", "genero": "Corrida", "tamanho": 20, "capa": "capas/need-for-speed-hot-pursuit-remastered.jpg"},
  {"id": "need-for-speed-rivals", "titulo": "Need for Speed Rivals", "genero": "Corrida", "tamanho": 20, "capa": "capas/need-for-speed-rivals.jpg"},
  {"id": "burnout-paradise-remastered", "titulo": "Burnout Paradise Remastered", "genero": "Corrida", "tamanho": 20, "capa": "capas/burnout-paradise-remastered.jpg"},
  {"id": "grid-legends", "titulo": "Grid Legends", "genero": "Corrida", "tamanho": 40, "capa": "capas/grid-legends.jpg"},
  {"id": "f1-23", "titulo": "F1 23", "genero": "Corrida", "tamanho": 80, "capa": "capas/f1-23.jpg"},
  {"id": "f1-24", "titulo": "F1 24", "genero": "Corrida", "tamanho": 80, "capa": "capas/f1-24.jpg"},
  {"id": "battlefield-1", "titulo": "Battlefield 1", "genero": "Tiro", "tamanho": 90, "capa": "capas/battlefield-1.jpg"},
  {"id": "battlefield-v", "titulo": "Battlefield V", "genero": "Tiro", "tamanho": 90, "capa": "capas/battlefield-v.jpg"},
  {"id": "battlefield-4", "titulo": "Battlefield 4", "genero": "Tiro", "tamanho": 60, "capa": "capas/battlefield-4.jpg"},
  {"id": "battlefield-2042", "titulo": "Battlefield 2042", "genero": "Tiro", "tamanho": 60, "capa": "capas/battlefield-2042.jpg"},
  {"id": "star-wars-jedi-fallen-order", "titulo": "Star Wars Jedi: Fallen Order", "genero": "Aventura", "tamanho": 50, "capa": "capas/star-wars-jedi-fallen-order.jpg"},
  {"id": "star-wars-battlefront-ii", "titulo": "Star Wars Battlefront II", "genero": "Tiro", "tamanho": 90, "capa": "capas/star-wars-battlefront-ii.jpg"},
  {"id": "star-wars-squadrons", "titulo": "Star Wars: Squadrons", "genero": "Ação", "tamanho": 40, "capa": "capas/star-wars-squadrons.jpg"},
  {"id": "mass-effect-legendary-edition", "titulo": "Mass Effect Legendary Edition", "genero": "RPG", "tamanho": 90, "capa": "capas/mass-effect-legendary-edition.jpg"},
  {"id": "dragon-age-inquisition", "titulo": "Dragon Age: Inquisition", "genero": "RPG", "tamanho": 50, "capa": "capas/dragon-age-inquisition.jpg"},
  {"id": "it-takes-two", "titulo": "It Takes Two", "genero": "Cooperativo", "tamanho": 50, "capa": "capas/it-takes-two.jpg"},
  {"id": "a-way-out", "titulo": "A Way Out", "genero": "Cooperativo", "tamanho": 30, "capa": "capas/a-way-out.jpg"},
  {"id": "unravel-two", "titulo": "Unravel Two", "genero": "Cooperativo", "tamanho": 3, "capa": "capas/unravel-two.jpg"},
  {"id": "plants-vs-zombies-batalha-por-neighborville", "titulo": "Plants vs. Zombies: Batalha por Neighborville", "genero": "Tiro", "tamanho": 25, "capa": "capas/plants-vs-zombies-batalha-por-neighborville.jpg"},
  {"id": "plants-vs-zombies-garden-warfare-2", "titulo": "Plants vs. Zombies Garden Warfare 2", "genero": "Tiro", "tamanho": 20, "capa": "capas/plants-vs-zombies-garden-warfare-2.jpg"},
  {"id": "apex-legends", "titulo": "Apex Legends", "genero": "Tiro", "tamanho": 70, "gratuito": true, "capa": "capas/apex-legends.jpg"},
  {"id": "titanfall-2", "titulo": "Titanfall 2", "genero": "Tiro", "tamanho": 50, "capa": "capas/titanfall-2.jpg"},
  {"id": "the-sims-4", "titulo": "The Sims 4", "genero": "Simulação", "tamanho": 25, "capa": "capas/the-sims-4.jpg"},
  {"id": "call-of-duty-black-ops-6", "titulo": "Call of Duty: Black Ops 6", "genero": "Tiro", "tamanho": 150, "capa": "capas/call-of-duty-black-ops-6.jpg"},
  {"id": "call-of-duty-modern-warfare-iii", "titulo": "Call of Duty: Modern Warfare III", "genero": "Tiro", "tamanho": 120, "capa": "capas/call-of-duty-modern-warfare-iii.jpg"},
  {"id": "call-of-duty-modern-warfare-ii", "titulo": "Call of Duty: Modern Warfare II", "genero": "Tiro", "tamanho": 120, "capa": "capas/call-of-duty-modern-warfare-ii.jpg"},
  {"id": "call-of-duty-vanguard", "titulo": "Call of Duty: Vanguard", "genero": "Tiro", "tamanho": 70, "capa": "capas/call-of-duty-vanguard.jpg"},
  {"id": "call-of-duty-black-ops-cold-war", "titulo": "Call of Duty: Black Ops Cold War", "genero": "Tiro", "tamanho": 95, "capa": "capas/call-of-duty-black-ops-cold-war.jpg"},
  {"id": "call-of-duty-modern-warfare-2019", "titulo": "Call of Duty: Modern Warfare (2019)", "genero": "Tiro", "tamanho": 175, "capa": "capas/call-of-duty-modern-warfare-2019.jpg"},
  {"id": "call-of-duty-black-ops-4", "titulo": "Call of Duty: Black Ops 4", "genero": "Tiro", "tamanho": 90, "capa": "capas/call-of-duty-black-ops-4.jpg"},
  {"id": "call-of-duty-wwii", "titulo": "Call of Duty: WWII", "genero": "Tiro", "tamanho": 90, "ranking": 13, "capa": "capas/call-of-duty-wwii.jpg"},
  {"id": "call-of-duty-black-ops-iii", "titulo": "Call of Duty: Black Ops III", "genero": "Tiro", "tamanho": 100, "ranking": 20, "capa": "capas/call-of-duty-black-ops-iii.jpg"},
  {"id": "call-of-duty-modern-warfare-remastered", "titulo": "Call of Duty: Modern Warfare Remastered", "genero": "Tiro", "tamanho": 50, "capa": "capas/call-of-duty-modern-warfare-remastered.jpg"},
  {"id": "call-of-duty-warzone", "titulo": "Call of Duty: Warzone", "genero": "Tiro", "tamanho": 100, "gratuito": true, "capa": "capas/call-of-duty-warzone.jpg"},
  {"id": "tony-hawk-s-pro-skater-1-2", "titulo": "Tony Hawk's Pro Skater 1 + 2", "genero": "Esporte", "tamanho": 20, "capa": "capas/tony-hawk-s-pro-skater-1-2.jpg"},
  {"id": "sekiro-shadows-die-twice", "titulo": "Sekiro: Shadows Die Twice", "genero": "RPG", "tamanho": 15, "capa": "capas/sekiro-shadows-die-twice.jpg"},
  {"id": "destiny-2", "titulo": "Destiny 2", "genero": "Tiro", "tamanho": 105, "gratuito": true, "capa": "capas/destiny-2.jpg"},
  {"id": "final-fantasy-vii-remake", "titulo": "Final Fantasy VII Remake", "genero": "RPG", "tamanho": 100, "ranking": 32, "capa": "capas/final-fantasy-vii-remake.jpg"},
  {"id": "final-fantasy-xv", "titulo": "Final Fantasy XV", "genero": "RPG", "tamanho": 100, "capa": "capas/final-fantasy-xv.jpg"},
  {"id": "final-fantasy-x-x-2-hd-remaster", "titulo": "Final Fantasy X/X-2 HD Remaster", "genero": "RPG", "tamanho": 40, "capa": "capas/final-fantasy-x-x-2-hd-remaster.jpg"},
  {"id": "final-fantasy-xii-the-zodiac-age", "titulo": "Final Fantasy XII: The Zodiac Age", "genero": "RPG", "tamanho": 35, "capa": "capas/final-fantasy-xii-the-zodiac-age.jpg"},
  {"id": "final-fantasy-vii", "titulo": "Final Fantasy VII", "genero": "RPG", "tamanho": 3, "capa": "capas/final-fantasy-vii.jpg"},
  {"id": "crisis-core-final-fantasy-vii-reunion", "titulo": "Crisis Core: Final Fantasy VII Reunion", "genero": "RPG", "tamanho": 15, "capa": "capas/crisis-core-final-fantasy-vii-reunion.jpg"},
  {"id": "kingdom-hearts-iii", "titulo": "Kingdom Hearts III", "genero": "RPG", "tamanho": 40, "capa": "capas/kingdom-hearts-iii.jpg"},
  {"id": "kingdom-hearts-hd-1-5-2-5-remix", "titulo": "Kingdom Hearts HD 1.5 + 2.5 ReMIX", "genero": "RPG", "tamanho": 50, "capa": "capas/kingdom-hearts-hd-1-5-2-5-remix.jpg"},
  {"id": "dragon-quest-xi-s", "titulo": "Dragon Quest XI S", "genero": "RPG", "tamanho": 25, "capa": "capas/dragon-quest-xi-s.jpg"},
  {"id": "nier-automata", "titulo": "NieR: Automata", "genero": "RPG", "tamanho": 50, "capa": "capas/nier-automata.jpg"},
  {"id": "marvel-s-avengers", "titulo": "Marvel's Avengers", "genero": "Ação", "tamanho": 90, "capa": "capas/marvel-s-avengers.jpg"},
  {"id": "marvel-s-guardians-of-the-galaxy", "titulo": "Marvel's Guardians of the Galaxy", "genero": "Ação", "tamanho": 80, "capa": "capas/marvel-s-guardians-of-the-galaxy.jpg"},
  {"id": "shadow-of-the-tomb-raider", "titulo": "Shadow of the Tomb Raider", "genero": "Aventura", "tamanho": 40, "capa": "capas/shadow-of-the-tomb-raider.jpg"},
  {"id": "rise-of-the-tomb-raider", "titulo": "Rise of the Tomb Raider", "genero": "Aventura", "tamanho": 25, "capa": "capas/rise-of-the-tomb-raider.jpg"},
  {"id": "tomb-raider-definitive-edition", "titulo": "Tomb Raider: Definitive Edition", "genero": "Aventura", "tamanho": 30, "capa": "capas/tomb-raider-definitive-edition.jpg"},
  {"id": "just-cause-3", "titulo": "Just Cause 3", "genero": "Ação", "tamanho": 50, "capa": "capas/just-cause-3.jpg"},
  {"id": "just-cause-4", "titulo": "Just Cause 4", "genero": "Ação", "tamanho": 45, "capa": "capas/just-cause-4.jpg"},
  {"id": "life-is-strange", "titulo": "Life is Strange", "genero": "Aventura", "tamanho": 15, "capa": "capas/life-is-strange.jpg"},
  {"id": "life-is-strange-true-colors", "titulo": "Life is Strange: True Colors", "genero": "Aventura", "tamanho": 25, "capa": "capas/life-is-strange-true-colors.jpg"},
  {"id": "resident-evil-2", "titulo": "Resident Evil 2", "genero": "Terror", "tamanho": 25, "capa": "capas/resident-evil-2.jpg"},
  {"id": "resident-evil-3", "titulo": "Resident Evil 3", "genero": "Terror", "tamanho": 30, "capa": "capas/resident-evil-3.jpg"},
  {"id": "resident-evil-4", "titulo": "Resident Evil 4", "genero": "Terror", "tamanho": 60, "ranking": 8, "capa": "capas/resident-evil-4.jpg"},
  {"id": "resident-evil-7-biohazard", "titulo": "Resident Evil 7: Biohazard", "genero": "Terror", "tamanho": 25, "capa": "capas/resident-evil-7-biohazard.jpg"},
  {"id": "resident-evil-village", "titulo": "Resident Evil Village", "genero": "Terror", "tamanho": 30, "capa": "capas/resident-evil-village.jpg"},
  {"id": "resident-evil-hd-remaster", "titulo": "Resident Evil HD Remaster", "genero": "Terror", "tamanho": 15, "capa": "capas/resident-evil-hd-remaster.jpg"},
  {"id": "resident-evil-0", "titulo": "Resident Evil 0", "genero": "Terror", "tamanho": 15, "capa": "capas/resident-evil-0.jpg"},
  {"id": "resident-evil-5", "titulo": "Resident Evil 5", "genero": "Terror", "tamanho": 15, "capa": "capas/resident-evil-5.jpg"},
  {"id": "resident-evil-6", "titulo": "Resident Evil 6", "genero": "Terror", "tamanho": 20, "capa": "capas/resident-evil-6.jpg"},
  {"id": "monster-hunter-world", "titulo": "Monster Hunter: World", "genero": "RPG", "tamanho": 70, "capa": "capas/monster-hunter-world.jpg"},
  {"id": "monster-hunter-rise", "titulo": "Monster Hunter Rise", "genero": "RPG", "tamanho": 30, "capa": "capas/monster-hunter-rise.jpg"},
  {"id": "devil-may-cry-5", "titulo": "Devil May Cry 5", "genero": "Ação", "tamanho": 35, "capa": "capas/devil-may-cry-5.jpg"},
  {"id": "devil-may-cry-4-special-edition", "titulo": "Devil May Cry 4 Special Edition", "genero": "Ação", "tamanho": 25, "capa": "capas/devil-may-cry-4-special-edition.jpg"},
  {"id": "street-fighter-v", "titulo": "Street Fighter V", "genero": "Luta", "tamanho": 50, "capa": "capas/street-fighter-v.jpg"},
  {"id": "street-fighter-6", "titulo": "Street Fighter 6", "genero": "Luta", "tamanho": 60, "capa": "capas/street-fighter-6.jpg"},
  {"id": "marvel-vs-capcom-infinite", "titulo": "Marvel vs. Capcom: Infinite", "genero": "Luta", "tamanho": 30, "capa": "capas/marvel-vs-capcom-infinite.jpg"},
  {"id": "mega-man-11", "titulo": "Mega Man 11", "genero": "Plataforma", "tamanho": 6, "capa": "capas/mega-man-11.jpg"},
  {"id": "dragon-s-dogma-dark-arisen", "titulo": "Dragon's Dogma: Dark Arisen", "genero": "RPG", "tamanho": 15, "capa": "capas/dragon-s-dogma-dark-arisen.jpg"},
  {"id": "dead-rising-4", "titulo": "Dead Rising 4", "genero": "Ação", "tamanho": 50, "capa": "capas/dead-rising-4.jpg"},
  {"id": "dark-souls-remastered", "titulo": "Dark Souls Remastered", "genero": "RPG", "tamanho": 15, "capa": "capas/dark-souls-remastered.jpg"},
  {"id": "dark-souls-ii-scholar-of-the-first-sin", "titulo": "Dark Souls II: Scholar of the First Sin", "genero": "RPG", "tamanho": 15, "capa": "capas/dark-souls-ii-scholar-of-the-first-sin.jpg"},
  {"id": "dark-souls-iii", "titulo": "Dark Souls III", "genero": "RPG", "tamanho": 25, "capa": "capas/dark-souls-iii.jpg"},
  {"id": "elden-ring", "titulo": "Elden Ring", "genero": "RPG", "tamanho": 50, "capa": "capas/elden-ring.jpg"},
  {"id": "tekken-7", "titulo": "Tekken 7", "genero": "Luta", "tamanho": 60, "ranking": 25, "capa": "capas/tekken-7.jpg"},
  {"id": "dragon-ball-fighterz", "titulo": "Dragon Ball FighterZ", "genero": "Luta", "tamanho": 10, "ranking": 36, "capa": "capas/dragon-ball-fighterz.jpg"},
  {"id": "dragon-ball-z-kakarot", "titulo": "Dragon Ball Z: Kakarot", "genero": "RPG", "tamanho": 40, "capa": "capas/dragon-ball-z-kakarot.jpg"},
  {"id": "dragon-ball-xenoverse-2", "titulo": "Dragon Ball Xenoverse 2", "genero": "Luta", "tamanho": 30, "ranking": 34, "capa": "capas/dragon-ball-xenoverse-2.jpg"},
  {"id": "naruto-shippuden-ultimate-ninja-storm-4", "titulo": "Naruto Shippuden: Ultimate Ninja Storm 4", "genero": "Luta", "tamanho": 35, "ranking": 26, "capa": "capas/naruto-shippuden-ultimate-ninja-storm-4.jpg"},
  {"id": "naruto-x-boruto-ultimate-ninja-storm-connections", "titulo": "Naruto x Boruto Ultimate Ninja Storm Connections", "genero": "Luta", "tamanho": 30, "capa": "capas/naruto-x-boruto-ultimate-ninja-storm-connections.jpg"},
  {"id": "naruto-to-boruto-shinobi-striker", "titulo": "Naruto to Boruto: Shinobi Striker", "genero": "Luta", "tamanho": 20, "capa": "capas/naruto-to-boruto-shinobi-striker.jpg"},
  {"id": "one-piece-pirate-warriors-4", "titulo": "One Piece: Pirate Warriors 4", "genero": "Ação", "tamanho": 20, "capa": "capas/one-piece-pirate-warriors-4.jpg"},
  {"id": "one-piece-odyssey", "titulo": "One Piece Odyssey", "genero": "RPG", "tamanho": 30, "capa": "capas/one-piece-odyssey.jpg"},
  {"id": "jump-force", "titulo": "Jump Force", "genero": "Luta", "tamanho": 20, "capa": "capas/jump-force.jpg"},
  {"id": "demon-slayer-the-hinokami-chronicles", "titulo": "Demon Slayer: The Hinokami Chronicles", "genero": "Luta", "tamanho": 30, "capa": "capas/demon-slayer-the-hinokami-chronicles.jpg"},
  {"id": "jujutsu-kaisen-cursed-clash", "titulo": "Jujutsu Kaisen Cursed Clash", "genero": "Luta", "tamanho": 15, "capa": "capas/jujutsu-kaisen-cursed-clash.jpg"},
  {"id": "my-hero-one-s-justice-2", "titulo": "My Hero One's Justice 2", "genero": "Luta", "tamanho": 10, "capa": "capas/my-hero-one-s-justice-2.jpg"},
  {"id": "saint-seiya-soldiers-soul", "titulo": "Saint Seiya: Soldiers' Soul", "genero": "Luta", "tamanho": 15, "capa": "capas/saint-seiya-soldiers-soul.jpg"},
  {"id": "ni-no-kuni-ii-revenant-kingdom", "titulo": "Ni no Kuni II: Revenant Kingdom", "genero": "RPG", "tamanho": 30, "capa": "capas/ni-no-kuni-ii-revenant-kingdom.jpg"},
  {"id": "tales-of-arise", "titulo": "Tales of Arise", "genero": "RPG", "tamanho": 45, "capa": "capas/tales-of-arise.jpg"},
  {"id": "code-vein", "titulo": "Code Vein", "genero": "RPG", "tamanho": 30, "capa": "capas/code-vein.jpg"},
  {"id": "ace-combat-7-skies-unknown", "titulo": "Ace Combat 7: Skies Unknown", "genero": "Ação", "tamanho": 50, "capa": "capas/ace-combat-7-skies-unknown.jpg"},
  {"id": "soulcalibur-vi", "titulo": "Soulcalibur VI", "genero": "Luta", "tamanho": 25, "capa": "capas/soulcalibur-vi.jpg"},
  {"id": "little-nightmares", "titulo": "Little Nightmares", "genero": "Terror", "tamanho": 6, "capa": "capas/little-nightmares.jpg"},
  {"id": "little-nightmares-ii", "titulo": "Little Nightmares II", "genero": "Terror", "tamanho": 10, "capa": "capas/little-nightmares-ii.jpg"},
  {"id": "pac-man-world-re-pac", "titulo": "Pac-Man World Re-Pac", "genero": "Plataforma", "tamanho": 5, "capa": "capas/pac-man-world-re-pac.jpg"},
  {"id": "efootball", "titulo": "eFootball", "genero": "Esporte", "tamanho": 40, "gratuito": true, "capa": "capas/efootball.jpg"},
  {"id": "metal-gear-solid-v-the-phantom-pain", "titulo": "Metal Gear Solid V: The Phantom Pain", "genero": "Ação", "tamanho": 30, "capa": "capas/metal-gear-solid-v-the-phantom-pain.jpg"},
  {"id": "yu-gi-oh-master-duel", "titulo": "Yu-Gi-Oh! Master Duel", "genero": "Estratégia", "tamanho": 5, "gratuito": true, "capa": "capas/yu-gi-oh-master-duel.jpg"},
  {"id": "sonic-mania", "titulo": "Sonic Mania", "genero": "Plataforma", "tamanho": 1, "capa": "capas/sonic-mania.jpg"},
  {"id": "sonic-forces", "titulo": "Sonic Forces", "genero": "Plataforma", "tamanho": 15, "capa": "capas/sonic-forces.jpg"},
  {"id": "sonic-frontiers", "titulo": "Sonic Frontiers", "genero": "Plataforma", "tamanho": 25, "capa": "capas/sonic-frontiers.jpg"},
  {"id": "sonic-colors-ultimate", "titulo": "Sonic Colors: Ultimate", "genero": "Plataforma", "tamanho": 8, "capa": "capas/sonic-colors-ultimate.jpg"},
  {"id": "team-sonic-racing", "titulo": "Team Sonic Racing", "genero": "Corrida", "tamanho": 15, "capa": "capas/team-sonic-racing.jpg"},
  {"id": "persona-5-royal", "titulo": "Persona 5 Royal", "genero": "RPG", "tamanho": 40, "capa": "capas/persona-5-royal.jpg"},
  {"id": "persona-4-golden", "titulo": "Persona 4 Golden", "genero": "RPG", "tamanho": 15, "capa": "capas/persona-4-golden.jpg"},
  {"id": "persona-3-reload", "titulo": "Persona 3 Reload", "genero": "RPG", "tamanho": 30, "capa": "capas/persona-3-reload.jpg"},
  {"id": "yakuza-0", "titulo": "Yakuza 0", "genero": "Ação", "tamanho": 35, "capa": "capas/yakuza-0.jpg"},
  {"id": "yakuza-like-a-dragon", "titulo": "Yakuza: Like a Dragon", "genero": "RPG", "tamanho": 45, "capa": "capas/yakuza-like-a-dragon.jpg"},
  {"id": "judgment", "titulo": "Judgment", "genero": "Ação", "tamanho": 40, "capa": "capas/judgment.jpg"},
  {"id": "alien-isolation", "titulo": "Alien: Isolation", "genero": "Terror", "tamanho": 15, "capa": "capas/alien-isolation.jpg"},
  {"id": "two-point-hospital", "titulo": "Two Point Hospital", "genero": "Simulação", "tamanho": 5, "capa": "capas/two-point-hospital.jpg"},
  {"id": "hogwarts-legacy", "titulo": "Hogwarts Legacy", "genero": "RPG", "tamanho": 80, "capa": "capas/hogwarts-legacy.jpg"},
  {"id": "mortal-kombat-11", "titulo": "Mortal Kombat 11", "genero": "Luta", "tamanho": 70, "ranking": 11, "capa": "capas/mortal-kombat-11.jpg"},
  {"id": "mortal-kombat-x", "titulo": "Mortal Kombat X", "genero": "Luta", "tamanho": 40, "capa": "capas/mortal-kombat-x.jpg"},
  {"id": "injustice-2", "titulo": "Injustice 2", "genero": "Luta", "tamanho": 50, "capa": "capas/injustice-2.jpg"},
  {"id": "batman-arkham-knight", "titulo": "Batman: Arkham Knight", "genero": "Ação", "tamanho": 55, "capa": "capas/batman-arkham-knight.jpg"},
  {"id": "batman-return-to-arkham", "titulo": "Batman: Return to Arkham", "genero": "Ação", "tamanho": 70},
  {"id": "terra-media-sombras-de-mordor", "titulo": "Terra-média: Sombras de Mordor", "genero": "Ação", "tamanho": 40, "capa": "capas/terra-media-sombras-de-mordor.jpg"},
  {"id": "terra-media-sombras-da-guerra", "titulo": "Terra-média: Sombras da Guerra", "genero": "Ação", "tamanho": 60, "capa": "capas/terra-media-sombras-da-guerra.jpg"},
  {"id": "mad-max", "titulo": "Mad Max", "genero": "Ação", "tamanho": 30, "capa": "capas/mad-max.jpg"},
  {"id": "lego-star-wars-a-saga-skywalker", "titulo": "LEGO Star Wars: A Saga Skywalker", "genero": "Infantil", "tamanho": 40, "capa": "capas/lego-star-wars-a-saga-skywalker.jpg"},
  {"id": "lego-marvel-super-heroes-2", "titulo": "LEGO Marvel Super Heroes 2", "genero": "Infantil", "tamanho": 20, "capa": "capas/lego-marvel-super-heroes-2.jpg"},
  {"id": "lego-dc-super-villains", "titulo": "LEGO DC Super-Villains", "genero": "Infantil", "tamanho": 20, "capa": "capas/lego-dc-super-villains.jpg"},
  {"id": "lego-jurassic-world", "titulo": "LEGO Jurassic World", "genero": "Infantil", "tamanho": 10, "capa": "capas/lego-jurassic-world.jpg"},
  {"id": "lego-harry-potter-collection", "titulo": "LEGO Harry Potter Collection", "genero": "Infantil", "tamanho": 20},
  {"id": "lego-os-incriveis", "titulo": "LEGO Os Incríveis", "genero": "Infantil", "tamanho": 15, "capa": "capas/lego-os-incriveis.jpg"},
  {"id": "lego-worlds", "titulo": "LEGO Worlds", "genero": "Infantil", "tamanho": 10, "capa": "capas/lego-worlds.jpg"},
  {"id": "lego-2k-drive", "titulo": "LEGO 2K Drive", "genero": "Corrida", "tamanho": 30, "capa": "capas/lego-2k-drive.jpg"},
  {"id": "dying-light", "titulo": "Dying Light", "genero": "Terror", "tamanho": 40, "capa": "capas/dying-light.jpg"},
  {"id": "dying-light-2", "titulo": "Dying Light 2", "genero": "Terror", "tamanho": 50, "capa": "capas/dying-light-2.jpg"},
  {"id": "nba-2k25", "titulo": "NBA 2K25", "genero": "Esporte", "tamanho": 100, "capa": "capas/nba-2k25.jpg"},
  {"id": "wwe-2k24", "titulo": "WWE 2K24", "genero": "Luta", "tamanho": 60, "capa": "capas/wwe-2k24.jpg"},
  {"id": "borderlands-3", "titulo": "Borderlands 3", "genero": "Tiro", "tamanho": 75, "capa": "capas/borderlands-3.jpg"},
  {"id": "borderlands-the-handsome-collection", "titulo": "Borderlands: The Handsome Collection", "genero": "Tiro", "tamanho": 40, "capa": "capas/borderlands-the-handsome-collection.jpg"},
  {"id": "tiny-tina-s-wonderlands", "titulo": "Tiny Tina's Wonderlands", "genero": "Tiro", "tamanho": 50, "capa": "capas/tiny-tina-s-wonderlands.jpg"},
  {"id": "bioshock-the-collection", "titulo": "BioShock: The Collection", "genero": "Tiro", "tamanho": 45, "capa": "capas/bioshock-the-collection.jpg"},
  {"id": "mafia-definitive-edition", "titulo": "Mafia: Definitive Edition", "genero": "Ação", "tamanho": 50, "capa": "capas/mafia-definitive-edition.jpg"},
  {"id": "mafia-iii", "titulo": "Mafia III", "genero": "Ação", "tamanho": 50, "capa": "capas/mafia-iii.jpg"},
  {"id": "xcom-2", "titulo": "XCOM 2", "genero": "Estratégia", "tamanho": 25, "capa": "capas/xcom-2.jpg"},
  {"id": "civilization-vi", "titulo": "Civilization VI", "genero": "Estratégia", "tamanho": 10, "capa": "capas/civilization-vi.jpg"},
  {"id": "the-elder-scrolls-v-skyrim-special-edition", "titulo": "The Elder Scrolls V: Skyrim Special Edition", "genero": "RPG", "tamanho": 15, "capa": "capas/the-elder-scrolls-v-skyrim-special-edition.jpg"},
  {"id": "fallout-4", "titulo": "Fallout 4", "genero": "RPG", "tamanho": 40, "capa": "capas/fallout-4.jpg"},
  {"id": "fallout-76", "titulo": "Fallout 76", "genero": "RPG", "tamanho": 80, "capa": "capas/fallout-76.jpg"},
  {"id": "the-elder-scrolls-online", "titulo": "The Elder Scrolls Online", "genero": "RPG", "tamanho": 100, "capa": "capas/the-elder-scrolls-online.jpg"},
  {"id": "doom", "titulo": "DOOM", "genero": "Tiro", "tamanho": 50, "capa": "capas/doom.jpg"},
  {"id": "doom-eternal", "titulo": "DOOM Eternal", "genero": "Tiro", "tamanho": 50, "capa": "capas/doom-eternal.jpg"},
  {"id": "wolfenstein-ii-the-new-colossus", "titulo": "Wolfenstein II: The New Colossus", "genero": "Tiro", "tamanho": 50, "capa": "capas/wolfenstein-ii-the-new-colossus.jpg"},
  {"id": "wolfenstein-the-new-order", "titulo": "Wolfenstein: The New Order", "genero": "Tiro", "tamanho": 40, "capa": "capas/wolfenstein-the-new-order.jpg"},
  {"id": "prey", "titulo": "Prey", "genero": "Tiro", "tamanho": 25, "capa": "capas/prey.jpg"},
  {"id": "dishonored-2", "titulo": "Dishonored 2", "genero": "Ação", "tamanho": 35, "capa": "capas/dishonored-2.jpg"},
  {"id": "the-witcher-3-wild-hunt-complete-edition", "titulo": "The Witcher 3: Wild Hunt – Complete Edition", "genero": "RPG", "tamanho": 70, "ranking": 15, "capa": "capas/the-witcher-3-wild-hunt-complete-edition.jpg"},
  {"id": "cyberpunk-2077", "titulo": "Cyberpunk 2077", "genero": "RPG", "tamanho": 70, "capa": "capas/cyberpunk-2077.jpg"},
  {"id": "minecraft", "titulo": "Minecraft", "genero": "Infantil", "tamanho": 3, "ranking": 14, "capa": "capas/minecraft.jpg"},
  {"id": "minecraft-dungeons", "titulo": "Minecraft Dungeons", "genero": "Infantil", "tamanho": 6, "capa": "capas/minecraft-dungeons.jpg"},
  {"id": "fortnite", "titulo": "Fortnite", "genero": "Tiro", "tamanho": 40, "gratuito": true},
  {"id": "rocket-league", "titulo": "Rocket League", "genero": "Esporte", "tamanho": 20, "gratuito": true, "capa": "capas/rocket-league.jpg"},
  {"id": "fall-guys", "titulo": "Fall Guys", "genero": "Festa", "tamanho": 5, "gratuito": true, "capa": "capas/fall-guys.jpg"},
  {"id": "genshin-impact", "titulo": "Genshin Impact", "genero": "RPG", "tamanho": 90, "gratuito": true},
  {"id": "warframe", "titulo": "Warframe", "genero": "Tiro", "tamanho": 50, "gratuito": true, "capa": "capas/warframe.jpg"},
  {"id": "brawlhalla", "titulo": "Brawlhalla", "genero": "Luta", "tamanho": 2, "gratuito": true, "capa": "capas/brawlhalla.jpg"},
  {"id": "roblox", "titulo": "Roblox", "genero": "Infantil", "tamanho": 3, "gratuito": true},
  {"id": "overwatch-2", "titulo": "Overwatch 2", "genero": "Tiro", "tamanho": 50, "gratuito": true, "capa": "capas/overwatch-2.jpg"},
  {"id": "war-thunder", "titulo": "War Thunder", "genero": "Ação", "tamanho": 60, "gratuito": true, "capa": "capas/war-thunder.jpg"},
  {"id": "pubg-battlegrounds", "titulo": "PUBG: Battlegrounds", "genero": "Tiro", "tamanho": 40, "gratuito": true, "capa": "capas/pubg-battlegrounds.jpg"},
  {"id": "hollow-knight", "titulo": "Hollow Knight", "genero": "Plataforma", "tamanho": 7, "capa": "capas/hollow-knight.jpg"},
  {"id": "celeste", "titulo": "Celeste", "genero": "Plataforma", "tamanho": 2, "capa": "capas/celeste.jpg"},
  {"id": "cuphead", "titulo": "Cuphead", "genero": "Plataforma", "tamanho": 7, "capa": "capas/cuphead.jpg"},
  {"id": "stardew-valley", "titulo": "Stardew Valley", "genero": "Simulação", "tamanho": 1, "capa": "capas/stardew-valley.jpg"},
  {"id": "terraria", "titulo": "Terraria", "genero": "Aventura", "tamanho": 1, "capa": "capas/terraria.jpg"},
  {"id": "dead-cells", "titulo": "Dead Cells", "genero": "Ação", "tamanho": 2, "capa": "capas/dead-cells.jpg"},
  {"id": "hades", "titulo": "Hades", "genero": "Ação", "tamanho": 10, "capa": "capas/hades.jpg"},
  {"id": "undertale", "titulo": "Undertale", "genero": "RPG", "tamanho": 1, "capa": "capas/undertale.jpg"},
  {"id": "inside", "titulo": "Inside", "genero": "Aventura", "tamanho": 3, "capa": "capas/inside.jpg"},
  {"id": "limbo", "titulo": "Limbo", "genero": "Aventura", "tamanho": 1, "capa": "capas/limbo.jpg"},
  {"id": "overcooked-all-you-can-eat", "titulo": "Overcooked! All You Can Eat", "genero": "Cooperativo", "tamanho": 15, "capa": "capas/overcooked-all-you-can-eat.jpg"},
  {"id": "overcooked-2", "titulo": "Overcooked! 2", "genero": "Cooperativo", "tamanho": 5, "capa": "capas/overcooked-2.jpg"},
  {"id": "moving-out", "titulo": "Moving Out", "genero": "Cooperativo", "tamanho": 5, "capa": "capas/moving-out.jpg"},
  {"id": "human-fall-flat", "titulo": "Human: Fall Flat", "genero": "Cooperativo", "tamanho": 5, "capa": "capas/human-fall-flat.jpg"},
  {"id": "among-us", "titulo": "Among Us", "genero": "Festa", "tamanho": 1, "capa": "capas/among-us.jpg"},
  {"id": "cult-of-the-lamb", "titulo": "Cult of the Lamb", "genero": "Ação", "tamanho": 5, "capa": "capas/cult-of-the-lamb.jpg"},
  {"id": "stray", "titulo": "Stray", "genero": "Aventura", "tamanho": 10, "capa": "capas/stray.jpg"},
  {"id": "subnautica", "titulo": "Subnautica", "genero": "Aventura", "tamanho": 10, "capa": "capas/subnautica.jpg"},
  {"id": "subnautica-below-zero", "titulo": "Subnautica: Below Zero", "genero": "Aventura", "tamanho": 10, "capa": "capas/subnautica-below-zero.jpg"},
  {"id": "ark-survival-evolved", "titulo": "ARK: Survival Evolved", "genero": "Aventura", "tamanho": 100, "capa": "capas/ark-survival-evolved.jpg"},
  {"id": "the-forest", "titulo": "The Forest", "genero": "Terror", "tamanho": 7, "capa": "capas/the-forest.jpg"},
  {"id": "no-man-s-sky", "titulo": "No Man's Sky", "genero": "Aventura", "tamanho": 15, "capa": "capas/no-man-s-sky.jpg"},
  {"id": "don-t-starve-together", "titulo": "Don't Starve Together", "genero": "Aventura", "tamanho": 3, "capa": "capas/don-t-starve-together.jpg"},
  {"id": "dead-by-daylight", "titulo": "Dead by Daylight", "genero": "Terror", "tamanho": 45, "capa": "capas/dead-by-daylight.jpg"},
  {"id": "outlast", "titulo": "Outlast", "genero": "Terror", "tamanho": 5, "capa": "capas/outlast.jpg"},
  {"id": "outlast-2", "titulo": "Outlast 2", "genero": "Terror", "tamanho": 30, "capa": "capas/outlast-2.jpg"},
  {"id": "five-nights-at-freddy-s-security-breach", "titulo": "Five Nights at Freddy's: Security Breach", "genero": "Terror", "tamanho": 80, "capa": "capas/five-nights-at-freddy-s-security-breach.jpg"},
  {"id": "five-nights-at-freddy-s-help-wanted", "titulo": "Five Nights at Freddy's: Help Wanted", "genero": "Terror", "tamanho": 6, "capa": "capas/five-nights-at-freddy-s-help-wanted.jpg"},
  {"id": "bendy-and-the-ink-machine", "titulo": "Bendy and the Ink Machine", "genero": "Terror", "tamanho": 5, "capa": "capas/bendy-and-the-ink-machine.jpg"},
  {"id": "the-evil-within-2", "titulo": "The Evil Within 2", "genero": "Terror", "tamanho": 40, "capa": "capas/the-evil-within-2.jpg"},
  {"id": "the-quarry", "titulo": "The Quarry", "genero": "Terror", "tamanho": 50, "capa": "capas/the-quarry.jpg"},
  {"id": "nioh", "titulo": "Nioh", "genero": "RPG", "tamanho": 40, "capa": "capas/nioh.jpg"},
  {"id": "nioh-2", "titulo": "Nioh 2", "genero": "RPG", "tamanho": 40, "capa": "capas/nioh-2.jpg"},
  {"id": "lies-of-p", "titulo": "Lies of P", "genero": "RPG", "tamanho": 40, "capa": "capas/lies-of-p.jpg"},
  {"id": "hitman-world-of-assassination", "titulo": "Hitman: World of Assassination", "genero": "Ação", "tamanho": 80, "capa": "capas/hitman-world-of-assassination.jpg"},
  {"id": "sniper-elite-4", "titulo": "Sniper Elite 4", "genero": "Tiro", "tamanho": 40, "capa": "capas/sniper-elite-4.jpg"},
  {"id": "sniper-elite-5", "titulo": "Sniper Elite 5", "genero": "Tiro", "tamanho": 50, "capa": "capas/sniper-elite-5.jpg"},
  {"id": "payday-2", "titulo": "Payday 2", "genero": "Tiro", "tamanho": 40, "capa": "capas/payday-2.jpg"},
  {"id": "back-4-blood", "titulo": "Back 4 Blood", "genero": "Tiro", "tamanho": 50, "capa": "capas/back-4-blood.jpg"},
  {"id": "world-war-z", "titulo": "World War Z", "genero": "Tiro", "tamanho": 40, "capa": "capas/world-war-z.jpg"},
  {"id": "metro-exodus", "titulo": "Metro Exodus", "genero": "Tiro", "tamanho": 60, "capa": "capas/metro-exodus.jpg"},
  {"id": "control", "titulo": "Control", "genero": "Ação", "tamanho": 40, "capa": "capas/control.jpg"},
  {"id": "alan-wake-remastered", "titulo": "Alan Wake Remastered", "genero": "Terror", "tamanho": 30, "capa": "capas/alan-wake-remastered.jpg"},
  {"id": "kena-bridge-of-spirits", "titulo": "Kena: Bridge of Spirits", "genero": "Aventura", "tamanho": 25, "capa": "capas/kena-bridge-of-spirits.jpg"},
  {"id": "a-plague-tale-innocence", "titulo": "A Plague Tale: Innocence", "genero": "Aventura", "tamanho": 40, "capa": "capas/a-plague-tale-innocence.jpg"},
  {"id": "diablo-iv", "titulo": "Diablo IV", "genero": "RPG", "tamanho": 90, "capa": "capas/diablo-iv.jpg"},
  {"id": "diablo-iii-eternal-collection", "titulo": "Diablo III: Eternal Collection", "genero": "RPG", "tamanho": 25, "capa": "capas/diablo-iii-eternal-collection.jpg"},
  {"id": "divinity-original-sin-2", "titulo": "Divinity: Original Sin 2", "genero": "RPG", "tamanho": 50, "capa": "capas/divinity-original-sin-2.jpg"},
  {"id": "kingdom-come-deliverance", "titulo": "Kingdom Come: Deliverance", "genero": "RPG", "tamanho": 40, "capa": "capas/kingdom-come-deliverance.jpg"},
  {"id": "sleeping-dogs-definitive-edition", "titulo": "Sleeping Dogs: Definitive Edition", "genero": "Ação", "tamanho": 20, "capa": "capas/sleeping-dogs-definitive-edition.jpg"},
  {"id": "guilty-gear-strive", "titulo": "Guilty Gear Strive", "genero": "Luta", "tamanho": 20, "capa": "capas/guilty-gear-strive.jpg"},
  {"id": "the-king-of-fighters-xv", "titulo": "The King of Fighters XV", "genero": "Luta", "tamanho": 60, "capa": "capas/the-king-of-fighters-xv.jpg"},
  {"id": "dirt-rally-2-0", "titulo": "Dirt Rally 2.0", "genero": "Corrida", "tamanho": 40, "capa": "capas/dirt-rally-2-0.jpg"},
  {"id": "project-cars-2", "titulo": "Project CARS 2", "genero": "Corrida", "tamanho": 40, "capa": "capas/project-cars-2.jpg"},
  {"id": "assetto-corsa-competizione", "titulo": "Assetto Corsa Competizione", "genero": "Corrida", "tamanho": 40, "capa": "capas/assetto-corsa-competizione.jpg"},
  {"id": "hot-wheels-unleashed", "titulo": "Hot Wheels Unleashed", "genero": "Corrida", "tamanho": 15, "capa": "capas/hot-wheels-unleashed.jpg"},
  {"id": "wreckfest", "titulo": "Wreckfest", "genero": "Corrida", "tamanho": 30, "capa": "capas/wreckfest.jpg"},
  {"id": "patrulha-canina-grand-prix", "titulo": "Patrulha Canina: Grand Prix", "genero": "Infantil", "tamanho": 5, "capa": "capas/patrulha-canina-grand-prix.jpg"},
  {"id": "bluey-o-videogame", "titulo": "Bluey: O Videogame", "genero": "Infantil", "tamanho": 5, "capa": "capas/bluey-o-videogame.jpg"},
  {"id": "bob-esponja-battle-for-bikini-bottom-rehydrated", "titulo": "Bob Esponja: Battle for Bikini Bottom – Rehydrated", "genero": "Infantil", "tamanho": 6, "capa": "capas/bob-esponja-battle-for-bikini-bottom-rehydrated.jpg"},
  {"id": "jurassic-world-evolution-2", "titulo": "Jurassic World Evolution 2", "genero": "Simulação", "tamanho": 15, "capa": "capas/jurassic-world-evolution-2.jpg"},
  {"id": "cities-skylines", "titulo": "Cities: Skylines", "genero": "Simulação", "tamanho": 7, "capa": "capas/cities-skylines.jpg"},
  {"id": "farming-simulator-22", "titulo": "Farming Simulator 22", "genero": "Simulação", "tamanho": 25, "capa": "capas/farming-simulator-22.jpg"},
  {"id": "powerwash-simulator", "titulo": "PowerWash Simulator", "genero": "Simulação", "tamanho": 5, "capa": "capas/powerwash-simulator.jpg"}
];
